services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  environment:
    RABBITMQ_DEFAULT_USER: simple
    RABBITMQ_DEFAULT_PASS: password
  tty:
    true