services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
#  environment:
#    RABBITMQ_DEFAULT_USER: coworking_username
#    RABBITMQ_DEFAULT_PASS: coworking_password